version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: .setup/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: alxbb_chain_of_responsibility
    container_name: alxbb_chain_of_responsibility_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - nginx
  nginx:
    image: nginx
    container_name: alxbb_chain_of_responsibility_pattern_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.setup/nginx/default.conf:/etc/nginx/conf.d/default.conf
  mail:
    container_name: sys_mail
    restart: unless-stopped
    image: eaudeweb/mailtrap:latest
    ports:
      - "8125:80"
      - "2525:25"
    environment:
      - MT_USER=mailtrap
      - MT_PASSWD=mailtrap
      - MT_MAILBOX_LIMIT=512000001
      - MT_MESSAGE_LIMIT=102400001